apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: story-pvc
spec:
  volumeName: story-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: standard

  resources:
    requests:
      storage: 1Gi
